### ISSUE TITLE
Split the library

### ISSUE THREAD

**Issue by bixuanzju** [hkuplg/fcore#172] opened 2015-04-30 07:34 UTC
Split the fcore from the front-end

**Comment by tomtau** [comment] 2015-05-02 15:02
In other words, the stuff related to the "f2j" language (i.e. described here https://github.com/hkuplg/fcore/tree/develop/doc/spec ) should be put into a different repository, referencing this one.

**Comment by zhiyuanshi** [comment] 2015-05-06 14:02
Duplicate of Issue #64.

**Closed as completed by zhiyuanshi** 2015-05-06 14:02 UTC
